server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=medicare-sql-server;encrypt=false
    username: sa
    password: SenhaExemplo2024!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: medicine
